### PR TITLE
Test branch

### PR DESCRIPTION
**Pull request by Gjuuuy**
Team page added

### CODE REVIEW

**Review by Mamadou2727 — COMMENTED** [review]
Waouh
Good Job Big Man
I have reviewed your work, and it looks clean.

**Review by Mamadou2727 — COMMENTED** [review]
By the way, Nice picture 👍

**Comment by Gjuuuy** [comment]
Thanks, appreciate it

**Review by Mamadou2727 — COMMENTED** [review]
Seems there is no error. I am going to test it locally.

**Comment by Gjuuuy** [comment]
Alright

**Pull request merged**
